[package]
name = "mnist_cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
mnist_lib = { path = "../mnist_lib" }
fhe_ckks = { path = "../fhe_ckks" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
rand = "0.8"